CREATE TABLE IF NOT EXISTS "ports" (
    "id" BIGSERIAL PRIMARY KEY,
    "ip" TEXT NOT NULL,
    "port_25_open" BOOLEAN NOT NULL,
    "domain" TEXT NOT NULL
);

-- pub id: i64,
-- 	pub domain: String,
-- 	pub bimi_used: bool,
-- 	pub bimi_version: String,
-- 	pub bimi_url_sender: String,
-- 	pub bimi_url_policy: String,
-- 	pub bimi_url_reputation: String,
-- 	pub bimi_hash: String,
-- 	pub bimi_s: String,
-- 	pub certificate_used: bool,
-- 	pub certificate_signature_algorithm_server: String,
-- 	pub certificate_issuer_server_city: String,
-- 	pub certificate_issuer_server_state: String,
-- 	pub certificate_issuer_server_locality: String,
-- 	pub certificate_issuer_server_organization: String,
-- 	pub certificate_issuer_server_common_name: String,
-- 	pub certificate_validity_server_not_before: String,
-- 	pub certificate_validity_server_not_after: String,
-- 	pub certificate_validity_server_is_valid: bool,
-- 	pub certificate_subject_server_city: String,
-- 	pub certificate_subject_server_state: String,
-- 	pub certificate_subject_server_locality: String,
-- 	pub certificate_subject_server_organization: String,
-- 	pub certificate_subject_server_common_name: String,
-- 	pub certificate_extensions_server_subject_alternative_names: Vec<String>,
-- 	pub certificate_signature_algorithm_intermediate: String,
-- 	pub certificate_issuer_intermediate_city: String,
-- 	pub certificate_issuer_intermediate_state: String,
-- 	pub certificate_issuer_intermediate_locality: String,
-- 	pub certificate_issuer_intermediate_organization: String,
-- 	pub certificate_issuer_intermediate_common_name: String,
-- 	pub certificate_validity_intermediate_not_before: String,
-- 	pub certificate_validity_intermediate_not_after: String,
-- 	pub certificate_subject_intermediate_city: String,
-- 	pub certificate_subject_intermediate_state: String,
-- 	pub certificate_subject_intermediate_locality: String,
-- 	pub certificate_subject_intermediate_organization: String,
-- 	pub certificate_subject_intermediate_common_name: String,
-- 	pub certificate_extensions_intermediate_subject_alternative_names: Vec<String>,
-- 	pub dane_used: bool,
-- 	pub dane_certificate_shape: i32,
-- 	pub dane_certificate_signature: bool,
-- 	pub dane_hash_presence: bool,
-- 	pub dane_hash: String,
-- 	pub dane_public_key_signature: bool,
-- 	pub dmarc_used: bool,
-- 	pub dmarc_v: String,
-- 	pub dmarc_adkim: String,
-- 	pub dmarc_aspf: String,
-- 	pub dmarc_fo: String,
-- 	pub dmarc_p: String,
-- 	pub dmarc_pct: i32,
-- 	pub dmarc_sp: String,
-- 	pub dmarc_rf: String,
-- 	pub dmarc_ri: String,
-- 	pub dmarc_rua: String,
-- 	pub dmarc_ruf: String,
-- 	pub mta_used: bool,
-- 	pub mta_version: String,
-- 	pub mta_sn: String,
-- 	pub spf_used: bool,
-- 	pub spf_version: String,
-- 	pub spf_mechanisms: Vec<String>,
-- 	pub spf_qualifier: String,
-- 	pub spf_ip: Vec<String>,
-- 	pub spf_include: Vec<String>,
-- 	pub spf_all: String,
-- 	pub tls_rpt_used: bool,
-- 	pub tls_rpt_v: String,
-- 	pub tls_rpt_rua: String,
CREATE TABLE IF NOT EXISTS "domains" (
    "id" BIGSERIAL PRIMARY KEY,
    "domain" TEXT NOT NULL,
    "bimi_used" BOOLEAN NOT NULL,
    "bimi_version" TEXT NOT NULL,
    "bimi_url_sender" TEXT NOT NULL,
    "bimi_url_policy" TEXT NOT NULL,
    "bimi_url_reputation" TEXT NOT NULL,
    "bimi_hash" TEXT NOT NULL,
    "bimi_s" TEXT NOT NULL,
--     "certificate_used" BOOLEAN NOT NULL,
--     "certificate_signature_algorithm_server" TEXT NOT NULL,
--     "certificate_issuer_server_city" TEXT NOT NULL,
--     "certificate_issuer_server_state" TEXT NOT NULL,
--     "certificate_issuer_server_locality" TEXT NOT NULL,
--     "certificate_issuer_server_organization" TEXT NOT NULL,
--     "certificate_issuer_server_common_name" TEXT NOT NULL,
--     "certificate_validity_server_not_before" TEXT NOT NULL,
--     "certificate_validity_server_not_after" TEXT NOT NULL,
--     "certificate_validity_server_is_valid" BOOLEAN NOT NULL,
--     "certificate_subject_server_city" TEXT NOT NULL,
--     "certificate_subject_server_state" TEXT NOT NULL,
--     "certificate_subject_server_locality" TEXT NOT NULL,
--     "certificate_subject_server_organization" TEXT NOT NULL,
--     "certificate_subject_server_common_name" TEXT NOT NULL,
--     "certificate_extensions_server_subject_alternative_names" TEXT[] NOT NULL,
--     "certificate_signature_algorithm_intermediate" TEXT NOT NULL,
--     "certificate_issuer_intermediate_city" TEXT NOT NULL,
--     "certificate_issuer_intermediate_state" TEXT NOT NULL,
--     "certificate_issuer_intermediate_locality" TEXT NOT NULL,
--     "certificate_issuer_intermediate_organization" TEXT NOT NULL,
--     "certificate_issuer_intermediate_common_name" TEXT NOT NULL,
--     "certificate_validity_intermediate_not_before" TEXT NOT NULL,
--     "certificate_validity_intermediate_not_after" TEXT NOT NULL,
--     "certificate_subject_intermediate_city" TEXT NOT NULL,
--     "certificate_subject_intermediate_state" TEXT NOT NULL,
--     "certificate_subject_intermediate_locality" TEXT NOT NULL,
--     "certificate_subject_intermediate_organization" TEXT NOT NULL,
--     "certificate_subject_intermediate_common_name" TEXT NOT NULL,
--     "certificate_extensions_intermediate_subject_alternative_names" TEXT[] NOT NULL,
    "dane_used" BOOLEAN NOT NULL,
    "dane_certificate_shape" INTEGER NOT NULL,
    "dane_certificate_signature" BOOLEAN NOT NULL,
    "dane_hash_presence" BOOLEAN NOT NULL,
    "dane_hash" TEXT NOT NULL,
    "dane_public_key_signature" BOOLEAN NOT NULL,
    "dmarc_used" BOOLEAN NOT NULL,
    "dmarc_v" TEXT NOT NULL,
    "dmarc_adkim" TEXT NOT NULL,
    "dmarc_aspf" TEXT NOT NULL,
    "dmarc_fo" TEXT NOT NULL,
    "dmarc_p" TEXT NOT NULL,
    "dmarc_pct" INTEGER NOT NULL,
    "dmarc_sp" TEXT NOT NULL,
    "dmarc_rf" TEXT NOT NULL,
    "dmarc_ri" TEXT NOT NULL,
    "dmarc_rua" TEXT NOT NULL,
    "dmarc_ruf" TEXT NOT NULL,
    "mta_used" BOOLEAN NOT NULL,
    "mta_version" TEXT NOT NULL,
    "mta_sn" TEXT NOT NULL,
    "spf_used" BOOLEAN NOT NULL,
    "spf_version" TEXT NOT NULL,
    "spf_mechanisms" TEXT[] NOT NULL,
    "spf_qualifier" TEXT NOT NULL,
    "spf_ip" TEXT[] NOT NULL,
    "spf_include" TEXT[] NOT NULL,
    "spf_all" TEXT NOT NULL,
    "tls_rpt_used" BOOLEAN NOT NULL,
    "tls_rpt_v" TEXT NOT NULL,
    "tls_rpt_rua" TEXT NOT NULL,
);
