---
name: Markdown CI

on:
  push:
    branches:
      - main
    paths:
      - '**/**.md'
  pull_request:
    branches:
      - main
    paths:
      - '**/**.md'

jobs:
  markdown-lint:
    name: Lint changelog file
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Lint changelog file
        uses: avto-dev/markdown-lint@v1
        with:
          rules: '/lint/rules/changelog.js'
          config: '/lint/config/changelog.yml'
          args: './CHANGELOG.md'
