name: Yaml CI

on:
  push:
    branches:
      - main
    paths:
      - '**/**.yml'
  pull_request:
    branches:
      - main
    paths:
      - '**/**.yml'

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install yamllint
        run: pip install yamllint
        
      - name: Run yamllint
        run:  cd .github/workflows && yamllint
